### ISSUE TITLE
Option to disable reconnect does not work

### ISSUE THREAD

**Issue by andersmarkendahl** [Nordix/ctraffic#3]
## The problem
I am trying to use the option:
```
  -reconnect
    	Re-connect on failures (default true)
```
But it does not seem to take effect.

## My setup

Running ctraffic v0.5 locally.

Server:
`$ ctraffic -server`
Client:
`$ ctraffic -monitor -nconn 10 -timeout 10s -reconnect false`

## How to reproduce

During my test I simply restart the server and expect the connections to **not** try to re-establish.

```
$ ctraffic -monitor -nconn 10 -timeout 10s -reconnect false
Conn act/fail/connecting: 10/0/0, Packets send/rec/dropped: 10/10/0
Conn act/fail/connecting: 10/0/0, Packets send/rec/dropped: 20/20/0
Conn act/fail/connecting: 9/1/1, Packets send/rec/dropped: 30/29/0  <-- server restart
Conn act/fail/connecting: 10/10/0, Packets send/rec/dropped: 44/34/0
Conn act/fail/connecting: 10/10/0, Packets send/rec/dropped: 54/44/0
Conn act/fail/connecting: 10/10/0, Packets send/rec/dropped: 64/54/0
Conn act/fail/connecting: 10/10/0, Packets send/rec/dropped: 74/64/0
Conn act/fail/connecting: 10/10/0, Packets send/rec/dropped: 84/74/0
Conn act/fail/connecting: 10/10/0, Packets send/rec/dropped: 94/84/0
^C
```
As we can see, all connections are re-establishing after the disconnect.

**Comment by uablrek** [comment]
Golang requires a "=" for boolena flags, see;

https://stackoverflow.com/questions/27411691/how-to-pass-boolean-arguments-to-go-flags

Do;
```
ctraffic -monitor -nconn 10 -timeout 10s -reconnect=false
```
and it works as expected.
