### ISSUE TITLE
New parameter for source port list

### ISSUE THREAD

**Issue by alitta-german** [Nordix/ctraffic#7]
In our server environment if we would like to connect to a remote server and the packets to be routed back, we have to acquire a source port from which we can initiate the connection. Thus we have to predefine the source port as the automatically assigned ephemeral port won't work. 
My suggestion:
As ctraffic creates several connections in parallel, it needs several source ports as well, thus the parameter should be for example a comma separated list. In some cases it will be a huge list (for -nconn 100)
e.g.:
```text
-srcports=12345,54321,55555
```
Or maybe due to the possiblity of massive data set to be given, maybe it could be given as an environment variable.
But I'm open to any other solution for the issue.

**Comment by uablrek** [comment]
Fixed in v1.8.0 by the [-srcfile option](https://github.com/Nordix/ctraffic#source-addresses).

Since you only want to control the port you must repeat the source address of your test generator on every line and vary the port.
