### ISSUE TITLE
Race condition in GetIPString

### ISSUE THREAD

**Issue by olahg** [Nordix/ctraffic#9]
In https://github.com/Nordix/ctraffic/blob/9ba9b734e8dfec4e88ba125e09e3e6275d550898/cmd/ctraffic/main.go#L149
a common structure is accessed without any synchronization. This function is called from multiple go-routines from here:
https://github.com/Nordix/ctraffic/blob/9ba9b734e8dfec4e88ba125e09e3e6275d550898/cmd/ctraffic/main.go#L430

The result can be that sometimes two (or more) connect go routines get the same source address, so one (or more) connections will always "keep connecting", or that sometimes connect exits with a "ran out of source addresses" error message.

This problem is also present here:
https://github.com/Nordix/mconnect/blob/ece3fbf6b41fbc0487f2846ac51ae6a2d96dfc94/pkg/rndip/rndip.go#L9

**Comment by uablrek** [comment]
I recommend using some "Add" function from https://pkg.go.dev/sync/atomic, rather than a mutex. As done for all counters.

**Comment by uablrek** [comment]
Compare with
https://github.com/Nordix/ctraffic/blob/9ba9b734e8dfec4e88ba125e09e3e6275d550898/cmd/ctraffic/main.go#L420

Something like:
```go
	cursor := atomic.AddInt32(&p.cursor, 1) - 1
	if int(cursor) < len(p.addresses) {
		adr := p.addresses[cursor]
		return adr
	}
```
